project:
  type: website
  render:
  - "01*.qmd"
  - "*.qmd"

website:
  title: "TXCF Elections"
  sidebar:
    contents:
      - href: index.qmd
        text: Overview
      - auto: "*.qmd"
    tools:
      - icon: github
        href: https://github.com/utdata/txcf-elections
      - icon: question-circle
        href: https://journalism.utexas.edu/innovation/

format:
  html:
    theme: cosmo
    toc: true
    df-print: paged
    code-overflow: wrap